# CITATION:
# This Makefile format was made from previous Makefiles that recieved help
# from chat.openai.com for examples of how to compile multiple .cpp files

all: a.out

a.out: main.o
	g++ -std=c++17 main.o

clean:
	rm -f *.o a.out